name: "nix"

on:
  push:
    branches:
      - leafyrino

concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

env:
  NIX_PKGS_REF: nixos-25.05
  ATTIC_CACHE: ${{ vars.ATTIC_CACHE }}
  ATTIC_ENDPOINT: ${{ vars.ATTIC_ENDPOINT }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
  CACHIX_CACHE: ${{ vars.CACHIX_CACHE }}
  CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

jobs:
  nix:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Init Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/${{ env.NIX_PKGS_REF }}.tar.gz

      - name: Install Attic Client
        run: nix profile install --inputs-from https://github.com/NixOS/nixpkgs/archive/$NIX_PKGS_REF.tar.gz nixpkgs#attic-client

      - name: Attic Login
        run: attic login $ATTIC_CACHE $ATTIC_ENDPOINT $ATTIC_TOKEN

      - name: Install Cachix Client
        run: nix profile install --inputs-from https://github.com/NixOS/nixpkgs/archive/$NIX_PKGS_REF.tar.gz nixpkgs#cachix

      - name: Use Cachix Cache
        run: cachix use leafyrino

      - name: Build
        run: nix build .#package -L

      - name: Attic Push
        run: attic push $ATTIC_CACHE ./result

      - name: Cachix Push
        run: cachix push $CACHIX_CACHE ./result
